# These are supported funding model platforms

github: [tuo-username-github] # Sostituisci con il tuo username GitHub o organizzazione
patreon: caspermail
custom: ["https://caspermail.com/sponsor", "https://buymeacoffee.com/caspermail"]
