CREATE TABLE IF NOT EXISTS soc_siem_endpoints (
  tenant_id TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  auth_token TEXT,
  format VARCHAR(50) DEFAULT 'json',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
