apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-frontend
  namespace: caspermail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/utente81/caspmail-frontend:78f9b18570787c9eb2d54fd0aee52aa7bfcb168c
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          imagePullPolicy: Never
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config
              subPath: default.conf
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /var/run
              name: run-volume
            - mountPath: /var/log/nginx
              name: log-volume
      volumes:
        - name: html-volume
          hostPath:
            path: /home/ubuntu/caspmail/new/frontend/dist
            type: Directory
        - configMap:
            defaultMode: 420
            name: casper-frontend-config
          name: nginx-config
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
