apiVersion: v1
kind: ConfigMap
metadata:
  name: casper-frontend-config
  namespace: caspermail
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Auth and API routing will be handled by the Kubernetes Ingress, 
        # so we don't need proxy_pass in nginx anymore.
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-frontend
  namespace: caspermail
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: caspermail-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: casper-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: casper-frontend
  namespace: caspermail
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
