apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-frontend
  namespace: caspermail
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: caspermail-frontend:latest
        imagePullPolicy: Never
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: casper-frontend-config
        name: nginx-config
