---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: caspermail
spec:
  encryptedData:
    .dockerconfigjson: AgCsQtmZao4tPgT05rWO3i3CPz/h9dABI5xjAmhTvthCHvoQ/R/1rqgm63fv4n8dAWD5WDYyFyjqyCcfdakHhi9V1ooHxCDAcWcpTX5Cr/bpN82SOfJ/dObow6Yg/cgcsZgD+hn3sZCR1U+PlR+jC1mJoo6PlGO5tzvtPcz/P54CpfwqY9+uPPsMefZ5hwMi/u+4K5ZUxbl65MJbWUTGa0yhBk7CkInqMaNurw/ZXZmeN8rxSX9PpihywDiaVMgLqn2EQfcuI0At6FuOBya3mpEZWz1aHEZow9AogmJwbTs9JL9/jrXGalDttIzV1twOjo+BDlMColvYzlXvgaTmznsHNQakqNqFBeW+w8iUOBX4HzuYuxqvJKWoscw4yHBpsu21pie0Lq3xYpSZT//+P9muoSpoI6gbE2n5PVG1+GznwpHuwcWUmQu55Fla9bANzF66ySAPUszZ5RY70SV6MvDR9QAIOHtYmxPD1RgKKFQDicf4Xr+xssP5bPW0Nt9dWUrTq3HjbHSUQNr6X4K1loLkqJr66vbm5E+AINBnKaiztqHIw2bWCOqEuu/JKFyqiS04RtxrJ5hvkZV0u5pcRO4kUleRVA73AGOnFjlIQu2uSLhKh6pyB5wL734/B+081KBjaH5vLkd7wDFgicMf2DIL+AaG0htFWgcETFBzU76cKnw03E+Dy87mB7TT6z5zCIuNNeN3NF4DskWBjcTQZemVxPcfuiijgh2aMlRLNEM6l00JQX2FqMjHbtX1/YQFgHICW5cSMrBKWL5Gtni9Z/vROfR1aGjIhHSEazHf1LLn7C7aypSV9vVmeqcsR/cl8TTWZy2mzOurOtCsSWylRC9lWuWYrSJonAuARu+L/OsgMnweMoTFSo7kd6jzxFQdpWTWh0KxgsACDEv2PiKg+5u2kscdgpl+DlmZuHEWK0JR0GpyypU84cSO5MGbMH1RUJ0OJ4Kj+KHjlPJ/Hs04cHwZ
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: caspermail
    type: kubernetes.io/dockerconfigjson
