apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiVXRlbnRlODEiLCJwYXNzd29yZCI6ImdocF82Q0FKaVZsUTczbXY1R04xbk5IRFdsY2VuWHZlTlIySlhSQ1ciLCJlbWFpbCI6ImRldkBjYXNwZXJtYWlsLmxvY2FsIiwiYXV0aCI6IlZYUmxiblJsT0RFNloyaHdYelpEUVVwcFZteFJOek50ZGpWSFRqRnVUa2hFVjJ4alpXNVlkbVZPVWpKS1dGSkRWdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-07-18T07:29:21Z"
  name: ghcr-login-secret
  namespace: caspermail
  resourceVersion: "191059"
  uid: 90c3544b-a18c-41e6-9778-c1476eca6f75
type: kubernetes.io/dockerconfigjson
