apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: caspermail-caspermail-security-headers@kubernetescrd
  name: caspermail-ingress
  namespace: caspermail-enterprise
spec:
  rules:
  - host: enterprise.caspmail.com
    http:
      paths:
      - backend:
          service:
            name: casper-backend
            port:
              number: 3000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: casper-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: mail.enterprise.caspmail.com
    http:
      paths:
      - backend:
          service:
            name: casper-backend
            port:
              number: 3000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: casper-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: soc.enterprise.caspmail.com
    http:
      paths:
      - backend:
          service:
            name: casper-backend
            port:
              number: 3000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: casper-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: auth.enterprise.caspmail.com
    http:
      paths:
      - backend:
          service:
            name: casper-keycloak
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: db.enterprise.caspmail.com
    http:
      paths:
      - backend:
          service:
            name: pgadmin
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - enterprise.caspmail.com
    - mail.enterprise.caspmail.com
    - soc.enterprise.caspmail.com
    - auth.enterprise.caspmail.com
    - db.enterprise.caspmail.com
    secretName: caspermail-tls-secret
