apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caspermail-ingress
  namespace: caspermail
  annotations:
    kubernetes.io/ingress.class: traefik
    # Traefik specific annotations for routing
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: caspermail-caspermail-security-headers@kubernetescrd
spec:
  rules:
  - host: secure.internal
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: casper-backend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: casper-frontend
            port:
              number: 80
  - host: mail.secure.internal
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: casper-backend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: casper-frontend
            port:
              number: 80
  - host: soc.secure.internal
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: casper-backend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: casper-frontend
            port:
              number: 80
  - host: auth.secure.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: casper-keycloak
            port:
              number: 8080
  - host: db.secure.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 80
