apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: caspermail-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@caspermail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pgadmin_password
              name: casper-secrets
        - name: PGADMIN_SERVER_JSON_FILE
          value: /pgadmin4/servers.json
        image: dpage/pgadmin4:8.8@sha256:89ce52a67bf44d0ca18d22205b103e4488700c5305cecd5980528e472c2f36e3
        name: pgadmin
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: pgadmin-servers
          subPath: servers.json
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /var/lib/pgadmin
          name: pgadmin-data
      volumes:
      - configMap:
          name: pgadmin-servers
        name: pgadmin-servers
      - emptyDir: {}
        name: tmp-volume
      - emptyDir: {}
        name: pgadmin-data
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: caspermail-enterprise
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pgadmin
---
apiVersion: v1
data:
  servers.json: "{\n  \"Servers\": {\n    \"1\": {\n      \"Name\": \"Primary (Read-Write)\"\
    ,\n      \"Group\": \"Servers\",\n      \"Host\": \"casper-cnpg-rw\",\n      \"\
    Port\": 5432,\n      \"MaintenanceDB\": \"postgres\",\n      \"Username\": \"\
    caspermail\",\n      \"SSLMode\": \"prefer\"\n    },\n    \"2\": {\n      \"Name\"\
    : \"Replica (Read-Only)\",\n      \"Group\": \"Servers\",\n      \"Host\": \"\
    casper-pg-postgresql-read\",\n      \"Port\": 5432,\n      \"MaintenanceDB\":\
    \ \"postgres\",\n      \"Username\": \"caspermail\",\n      \"SSLMode\": \"prefer\"\
    \n    }\n  }\n}\n"
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: caspermail-enterprise
