apiVersion: v1
kind: Secret
metadata:
  name: casper-secrets
  namespace: caspermail
type: Opaque
stringData:
  postgres_password: "casper_db_password"
  keycloak_admin_password: "admin_secure_password"
  redis_password: "redis_secure_password"
