apiVersion: v1
data:
  stalwart.toml: '[server]

    hostname =  mail.caspmail.com


    [store.db]

    type = rocksdb

    path = /opt/stalwart/data


    [auth.default]

    type = internal


    [session.smtp.default]

    auth-require = true


    [directory.default]

    type = internal

    '
kind: ConfigMap
metadata:
  name: stalwart-config
  namespace: caspermail-enterprise
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stalwart-mail
  namespace: caspermail-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stalwart-mail
  template:
    metadata:
      labels:
        app: stalwart-mail
    spec:
      containers:
      - env:
        - name: STALWART_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: casper-stalwart-admin
              key: password
        image: stalwartlabs/mail-server:v0.9.3@sha256:edfb1774e2809ba32fd084246b4988cbf3f1b8c76f05b2ae7042157ac69193eb
        name: stalwart
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 587
          name: submission
        - containerPort: 465
          name: smtps
        - containerPort: 143
          name: imap
        - containerPort: 993
          name: imaps
        - containerPort: 8080
          name: jmap
        volumeMounts:
        - mountPath: /opt/stalwart/data
          name: stalwart-data
        - mountPath: /opt/stalwart/etc/stalwart.toml
          name: stalwart-config-volume
          subPath: stalwart.toml
      volumes:
      - name: stalwart-data
        persistentVolumeClaim:
          claimName: stalwart-data
      - configMap:
          name: stalwart-config
        name: stalwart-config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: stalwart-service
  namespace: caspermail-enterprise
spec:
  ports:
  - name: smtp
    port: 25
    targetPort: 25
  - name: submission
    port: 587
    targetPort: 587
  - name: smtps
    port: 465
    targetPort: 465
  - name: imap
    port: 143
    targetPort: 143
  - name: imaps
    port: 993
    targetPort: 993
  - name: jmap
    port: 8080
    targetPort: 8080
  selector:
    app: stalwart-mail
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data
  namespace: caspermail-enterprise
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
