apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transit-vault-data
  namespace: caspermail-enterprise
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transit-vault
  namespace: caspermail-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transit-vault
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transit-vault
    spec:
      initContainers:
      - name: cert-gen
        image: alpine/openssl:3.3.3
        command:
        - sh
        - -c
        - "set -e\nif [ ! -f /vault/tls/tls.crt ]; then\n  openssl req -x509 -newkey\
          \ rsa:4096 \\\n    -keyout /vault/tls/tls.key \\\n    -out /vault/tls/tls.crt\
          \ \\\n    -days 365 -nodes \\\n    -subj '/CN=transit-vault.caspermail-enterprise.svc.cluster.local'\
          \ \\\n    -addext 'subjectAltName=DNS:transit-vault,DNS:transit-vault.caspermail-enterprise.svc,DNS:transit-vault.caspermail-enterprise.svc.cluster.local'\n\
          \  chmod 600 /vault/tls/tls.key\n  chmod 644 /vault/tls/tls.crt\nfi\n"
        volumeMounts:
        - name: tls-certs
          mountPath: /vault/tls
      containers:
      - name: vault
        args:
        - server
        env:
        - name: VAULT_LOCAL_CONFIG
          value: '{"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":0,"tls_cert_file":"/vault/tls/tls.crt","tls_key_file":"/vault/tls/tls.key"}},"storage":{"file":{"path":"/vault/file"}},"ui":true}'
        - name: VAULT_ADDR
          value: https://transit-vault.caspermail-enterprise.svc.cluster.local:8200
        - name: VAULT_CACERT
          value: /vault/tls/tls.crt
        image: hashicorp/vault:1.15.2@sha256:0450896c43b13879b19442b204ce29dd19b5a10fce43d5cf38af17da20f56f4d
        ports:
        - containerPort: 8200
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - mountPath: /vault/file
          name: vault-data
        - mountPath: /vault/tls
          name: tls-certs
          readOnly: true
      nodeSelector:
        tier: secure-data
      tolerations:
      - effect: NoSchedule
        key: secure-data
        operator: Equal
        value: 'true'
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: transit-vault-data
      - name: tls-certs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: transit-vault
  namespace: caspermail-enterprise
spec:
  ports:
  - port: 8200
    targetPort: 8200
  selector:
    app: transit-vault
  type: ClusterIP
