apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: caspermail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: caspermail
data:
  vault.json: |
    {
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "storage": {
        "file": {
          "path": "/vault/file"
        }
      },
      "seal": {
        "transit": {
          "address": "http://192.168.189.203:30000",
          "disable_renewal": "false",
          "key_name": "autounseal",
          "mount_path": "transit",
          "tls_skip_verify": "true"
        }
      },
      "ui": true,
      "disable_mlock": true
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casper-vault
  namespace: caspermail
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15
        command: ["vault", "server", "-config=/vault/config/vault.json"]
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-unseal-token
              key: token
        ports:
        - containerPort: 8200
          name: http
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        volumeMounts:
        - name: config
          mountPath: /vault/config
        - name: data
          mountPath: /vault/file
      volumes:
      - name: config
        configMap:
          name: vault-config
      - name: data
        persistentVolumeClaim:
          claimName: vault-data
---
apiVersion: v1
kind: Service
metadata:
  name: casper-vault
  namespace: caspermail
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
