apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: caspermail-enterprise
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
data:
  vault.json: "{\n  \"listener\": {\n    \"tcp\": {\n      \"address\": \"0.0.0.0:8200\"\
    ,\n      \"tls_disable\": 0,\n      \"tls_cert_file\": \"/vault/tls/tls.crt\"\
    ,\n      \"tls_key_file\": \"/vault/tls/tls.key\"\n    }\n  },\n  \"storage\"\
    : {\n    \"file\": {\n      \"path\": \"/vault/file\"\n    }\n  },\n  \"seal\"\
    : {\n    \"transit\": {\n      \"address\": \"https://transit-vault:8200\",\n\
    \      \"disable_renewal\": \"false\",\n      \"key_name\": \"autounseal\",\n\
    \      \"mount_path\": \"transit\",\n      \"tls_skip_verify\": \"false\",
      \"tls_ca_cert\": \"/vault/transit-tls/ca.crt\"\n  \
    \  }\n  },\n  \"ui\": true,\n  \"disable_mlock\": true\n}"
kind: ConfigMap
metadata:
  name: vault-config
  namespace: caspermail-enterprise
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: casper-vault
  namespace: caspermail-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - command:
        - vault
        - server
        - -config=/vault/config/vault.json
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: vault-unseal-token
        image: hashicorp/vault:1.15@sha256:0450896c43b13879b19442b204ce29dd19b5a10fce43d5cf38af17da20f56f4d
        name: vault
        ports:
        - containerPort: 8200
          name: http
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - mountPath: /vault/config
          name: config
        - mountPath: /vault/file
          name: data
        - mountPath: /vault/tls
          name: tls
          readOnly: true
        - mountPath: /vault/transit-tls
          name: transit-tls
          readOnly: true
      nodeSelector:
        tier: secure-data
      tolerations:
      - effect: NoSchedule
        key: secure-data
        operator: Equal
        value: 'true'
      volumes:
      - configMap:
          name: vault-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: vault-data
      - name: tls
        secret:
          secretName: vault-tls
      - name: transit-tls
        secret:
          secretName: transit-vault-tls
---
apiVersion: v1
kind: Service
metadata:
  name: casper-vault
  namespace: caspermail-enterprise
spec:
  ports:
  - port: 8200
    targetPort: 8200
  selector:
    app: vault
