apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: caspermail
data:
  vault.json: |
    {
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "cluster_address": "0.0.0.0:8201",
          "tls_disable": 1
        }
      },
      "storage": {
        "raft": {
          "path": "/vault/file",
          "node_id": "NODE_ID",
          "retry_join": [
            {
              "leader_api_addr": "http://casper-vault-0.casper-vault-internal:8200"
            },
            {
              "leader_api_addr": "http://casper-vault-1.casper-vault-internal:8200"
            },
            {
              "leader_api_addr": "http://casper-vault-2.casper-vault-internal:8200"
            }
          ]
        }
      },
      "seal": {
        "transit": {
          "address": "http://casper-vault-kms.caspermail.svc.cluster.local:8200",
          "disable_renewal": "false",
          "key_name": "autounseal",
          "mount_path": "transit",
          "tls_skip_verify": "true"
        }
      },
      "ui": true,
      "disable_mlock": true
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casper-vault
  namespace: caspermail
  labels:
    app: vault
spec:
  serviceName: casper-vault-internal
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15
        command: ["/bin/sh", "-c", "sed 's/NODE_ID/'$POD_NAME'/g' /vault/config/vault.json > /tmp/vault.json && vault server -config=/tmp/vault.json"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VAULT_API_ADDR
          value: "http://$(POD_NAME).casper-vault-internal:8200"
        - name: VAULT_CLUSTER_ADDR
          value: "http://$(POD_NAME).casper-vault-internal:8201"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-unseal-token
              key: token
        ports:
        - containerPort: 8200
          name: http
        - containerPort: 8201
          name: server
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        volumeMounts:
        - name: config
          mountPath: /vault/config
        - name: data
          mountPath: /vault/file
      volumes:
      - name: config
        configMap:
          name: vault-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: casper-vault
  namespace: caspermail
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
