import PDFDocument from 'pdfkit';
import { pool } from '../db/index.mjs';

export async function generateSocReport(tenantId) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });

      // Gather data
      const { rows: kpiRows } = await pool.query(`
        SELECT
          COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days') as events_7d,
          COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days' AND severity IN ('critical', 'high')) as high_alerts_7d
        FROM soc_events
        WHERE tenant_id = $1
      `, [tenantId]);

      const { rows: casesRows } = await pool.query(`
        SELECT COUNT(*) as open_cases
        FROM soc_cases
        WHERE tenant_id = $1 AND status = 'open'
      `, [tenantId]);

      const eventsCount = kpiRows[0]?.events_7d || 0;
      const highAlerts = kpiRows[0]?.high_alerts_7d || 0;
      const openCases = casesRows[0]?.open_cases || 0;

      // Draw PDF
      doc.fontSize(24).font('Helvetica-Bold').fillColor('#0b1220').text('CaspMail SOC - Weekly Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).font('Helvetica').fillColor('#64748b').text(`Generated on: ${new Date().toUTCString()}`, { align: 'center' });
      doc.moveDown(3);

      doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a2535').text('Executive Summary');
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica').fillColor('#334155')
         .text(`Over the past 7 days, the SOC ingested a total of ${eventsCount} events.`);
      doc.text(`There were ${highAlerts} high/critical alerts detected.`);
      doc.text(`Currently, there are ${openCases} open security cases requiring analyst attention.`);
      doc.moveDown(2);

      // Simple Table / KPIs
      doc.fontSize(14).font('Helvetica-Bold').text('Key Performance Indicators');
      doc.moveDown();
      doc.font('Helvetica').fontSize(12);
      
      const kpis = [
        { label: 'Total Events (7d)', value: eventsCount },
        { label: 'Critical/High Alerts', value: highAlerts },
        { label: 'Open Cases', value: openCases },
        { label: 'Overall Posture', value: highAlerts > 100 ? 'Needs Attention' : 'Healthy' }
      ];

      kpis.forEach(kpi => {
        doc.text(`${kpi.label}: `, { continued: true }).font('Helvetica-Bold').text(kpi.value.toString());
        doc.font('Helvetica');
        doc.moveDown(0.5);
      });

      doc.moveDown(2);
      doc.fontSize(10).fillColor('#94a3b8').text('This is an automated report generated by CaspMail Security Operations Center.', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
