name: 'Dependency Review'
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
        with:
          persist-credentials: false
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4 # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, ISC, BSD-3-Clause, BSD-2-Clause, Unlicense
          deny-licenses: GPL-3.0, AGPL-3.0
